title: Brain morphology-based predictive modelling of pain sensitivity: a machine learning approach
description: A brain structural MRI based predictive model was designed and deployed, as a proof-of-concept that structural brain regions 
hold predictive yield for quantifying individual variability in pain sensitivity. The model can find potential applications in accute and chornic 
pain conditions.
theme: jekyll-theme-minimal
